using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TaskBook.Tools.FontsHandler
{
    static class Fonts
    {
        public const string SegoeUI = "Segoe UI";

        public static List<string> All { get; } = new List<string>
        {
            "Arial",
            "Courier New",
            "Times New Roman",
            "Symbol",
            "Wingdings",
            "Microsoft Sans Serif",
            "Segoe UI",
            "Tahoma",
            "Calibri",
            "Cambria",
            "Candara",
            "Consolas",
            "Constantias",
            "Corbel",
            "Arial Black",
            "Franklin Gothic Medium",
            "Georgia",
            "Impact",
            "Lucida Console",
            "Lucida Sans Console",
            "Marlett",
            "Palatino Linotype",
            "Segoe Print",
            "Segoe Script",
            "Trebuchet MS",
            "Verdana",
            "Webdings",
            "Batang/BatangChe",
            "DFKai-SB",
            "Dotum/DotumChe",
            "Fangsong",
            "Gulim/GulimChe",
            "Gungsuh/GungsuhChe",
            "KaiTi",
            "Malgun Gothic",
            "Meiryo",
            "Microsoft JhengHei",
            "Microsoft YaHei",
            "MingLiU_HKSCS/MingLiU_HKSCS-ExtB",
            "MingLiU-ExtB/PMingLiU-ExtB",
            "MS Gothic/MS PGothic/MS UI Gothic",
            "MS Mincho/MS PMincho",
            "SimHei",
            "Simsun/NSimsun",
            "SimSun-ExtB",
            "Andalus",
            "Arabic Typesetting",
            "Microsoft Uighur",
            "Simplified Arabic",
            "Traditional Arabic",
            "Aharoni Bold",
            "David",
            "FrankRuehl",
            "Gisha",
            "Levenim",
            "Miriam",
            "Narkisim",
            "Rod",
            "Angsana New/AngsanaUPC",
            "Browallia New/BrowalliaUPC",
            "Cordia New/CordiaUPC",
            "DilleniaUPC",
            "EucrosiUPC",
            "FreesiaUPC",
            "IrisUPC",
            "JasmineUPC",
            "KodchiangUPC",
            "Leelawadee",
            "LilyUPC",
            "Gautami",
            "Iskoola Pota",
            "Kalinga",
            "Kartika",
            "Latha",
            "Mangal",
            "Raavi",
            "Shruti",
            "Tunga",
            "Vrinda",
            "DaunPenh",
            "DokChampa",
            "Estrangelo Edessa",
            "Euphemia",
            "Microsoft Himalaya",
            "Microsoft Yi Baiti",
            "Mongolian Baiti",
            "MV Boli",
            "Nyala",
            "Plantagenet Cherokee",
            "Sylfaen"
        };
    }
}
